### ISSUE TITLE
If doesn't work with  versions of node >16.x.x

### ISSUE THREAD

**Issue by JohnSmall** [zoomoid/strapi-provider-upload-aws-s3-advanced#19]
**Describe the bug**
When installing with  node: 'v18.11.0', npm: '8.19.2' I get the warning

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'strapi-provider-upload-aws-s3-advanced@4.2.1',
npm WARN EBADENGINE   required: { node: '>=10.16.0 <=16.x.x', npm: '>=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.11.0', npm: '8.19.2' }
npm WARN EBADENGINE }
```
**To Reproduce**
1. Set up a machine or docker container with node v18.11.0 and npm 8.19.2
2. run `npm i strapi-provider-upload-aws-s3-advanced`
3. check the output
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'strapi-provider-upload-aws-s3-advanced@4.2.1',
npm WARN EBADENGINE   required: { node: '>=10.16.0 <=16.x.x', npm: '>=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.11.0', npm: '8.19.2' }
npm WARN EBADENGINE }
```

**Expected behavior**
It should install an run in recent versions of node and npm

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Docker container inside VSCode devcontainer running Debian GNU/Linux 11 (bullseye)
 - Browser N/A
 - Version N/A

**Additional context**

**Comment by zoomoid** [comment]
This is fixed with #23
