### ISSUE TITLE
[v4] Endpoint not working

### ISSUE THREAD

**Issue by Tragio** [zoomoid/strapi-provider-upload-aws-s3-advanced#3]
**Describe the bug**
Hello @zoomoid 👋  thank you for your work. I was using the Strapi S3 plugin and it was working but I need CDN so I moved for your own.

However, the `endpoint` seems not working. Because it's going to `xxx.s3.us-west-002.amazonaws.com` instead of the one I set on the `endpoint`.

```
error uploading object to s3 shows_thumbnail_6427cbb_0936efb5bfcfbc3a67c8c63b24ec77a8_1f37f7d009.jpg
Error: getaddrinfo ENOTFOUND xxx.s3.us-west-002.amazonaws.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'xxx.s3.us-west-002.amazonaws.com',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
[2022-01-09 23:20:48.543] error: getaddrinfo ENOTFOUND xxx.s3.us-west-002.amazonaws.com
Error: getaddrinfo ENOTFOUND xxx.s3.us-west-002.amazonaws.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
```

**To Reproduce**
```js
  upload: {
    config: {
      provider: 'strapi-provider-upload-aws-s3-advanced',
      providerOptions: {
        accessKeyId: env('AWS_ACCESS_KEY_ID'),
        secretAccessKey: env('AWS_ACCESS_SECRET'),
        region: env('AWS_REGION'),
        endpoint: 's3.us-west-002.backblazeb2.com',
        params: {
          bucket: env('AWS_BUCKET'),
        },
        baseUrl: env('CDN_BASE_URL'),
      },
    },
  },
```

Thank you very much!! 😄

**Comment by zoomoid** [comment]
Hey @Tragio thank you for highlighting this, you are absolutely right, setting custom endpoints is something I had not considered up until your issue. The aws-sdk exposes a lot more configurability than this strapi plugin accounts and I like your proposition of using object spread to allow any configuration that the aws-sdk accepts 👍

**Comment by zoomoid** [comment]
Will merge this at the soonest possible time, looks good!

**Comment by Tragio** [comment]
It's a community 😁 glad to contribute!
