### ISSUE TITLE
node 20 support

### ISSUE THREAD

**Issue by pranavks** [zoomoid/strapi-provider-upload-aws-s3-advanced#30]
Node 20 is LTS now. We are unable to upgrade to Node 20 because the package allows upto Node 18 only. It would be great to have this done.

**Comment by zoomoid** [comment]
Please consider moving to the in-tree provider of strapi, they included all functionality of this plugin over the last iterations, notably `baseUrl`, `prefix` (which they call `rootUrl`), and the use of TypeScript. If you run strapi with Node 20, i can assume your version is fairly recent and you should be able to just move the configuration over.

Closing this issue with regards to ab743a132624cc58415654f69476d7e686b2c271
