### ISSUE TITLE
cross site origin

### ISSUE THREAD

**Issue by arpecop** [zoomoid/strapi-provider-upload-aws-s3-advanced#6]
It's probably something not related to the plugin but I cannot see the media even its uploaded and accessible via the direct url, any idea how to fix 

![Screenshot 2022-01-16 at 21 00 24](https://user-images.githubusercontent.com/168974/149674080-1cb3edc6-0691-404c-8f53-3df4fa63986c.png)

**Comment by zoomoid** [comment]
If I remember correctly, @aaronclimbs addressed this for strapi v4: see https://github.com/zoomoid/strapi-provider-upload-aws-s3-advanced#image-previews

Let me know if this fixes the issue 👍

**Comment by arpecop** [comment]
Fixed , Thank you!
